version: '3.8'

services:
  webapp:
    container_name: reactivities-webapp
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
