FROM node:16.17.0-alpine3.16
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY ./package*.json .
RUN npm install --legacy-peer-deps

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
CMD npm start